name: Refresh Job Index

on:
  schedule:
    - cron: '0 6 * * *'   # runs 6am UTC daily
  workflow_dispatch:       # manual trigger button in GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt && pip install groq

      - name: Run pipeline
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python -m utils.pipeline

      - name: Push changes
        run: |
          git config user.name "Amal Sebastian"
          git config user.email "theamalsebastian@example.com"
          git add data/jobs_index/*
          git commit -m "update job index"
          git push
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Set remote with PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/theamalsebastian/job_search_assistant.git

